# Generated by Django 5.2.4 on 2025-07-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-updated_at", "-created_at"],
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
    ]
